// This file is autogenerated by the hyperschema compiler
// !!DO NOT EDIT THIS FILE!!
// Schema Version: 1

import CompactEncoding
import Foundation

public func encode<C: Codec>(_ codec: C, _ value: C.Value) throws -> Data {
  var state = State()
  codec.preencode(&state, value)
  state.allocate()
  try codec.encode(&state, value)
  return state.buffer
}

public func decode<C: Codec>(_ codec: C, _ data: Data) throws -> C.Value {
  var state = State(data)
  return try codec.decode(&state)
}

public enum SchemaDecodeError: Error {
  case unknownEnumVariant(type: String, tag: UInt)
  case unknownVersion(type: String, version: UInt)
}

// @wdk-core/log-type-enum
public enum LogTypeEnum {
  case info
  case error
  case debug
}

public struct LogTypeEnumCodec: Codec {
  public typealias Value = LogTypeEnum

  let _uint = Primitive.UInt()

  public init() {}

  public func preencode(_ state: inout State, _ value: LogTypeEnum) {
    switch value {
    case .info: _uint.preencode(&state, 1)
    case .error: _uint.preencode(&state, 2)
    case .debug: _uint.preencode(&state, 3)
    }
  }

  public func encode(_ state: inout State, _ value: LogTypeEnum) throws {
    switch value {
    case .info: try _uint.encode(&state, 1)
    case .error: try _uint.encode(&state, 2)
    case .debug: try _uint.encode(&state, 3)
    }
  }

  public func decode(_ state: inout State) throws -> LogTypeEnum {
    let tag = try _uint.decode(&state)
    switch tag {
    case 1: return .info
    case 2: return .error
    case 3: return .debug
    default: throw SchemaDecodeError.unknownEnumVariant(type: "LogTypeEnum", tag: tag)
    }
  }
}

public let logTypeEnum = LogTypeEnumCodec()

// @wdk-core/log-request
public struct LogRequest {
  public var type: LogTypeEnum?
  public var data: String?

  public init(type: LogTypeEnum? = nil, data: String? = nil) {
    self.type = type
    self.data = data
  }
}

public struct LogRequestCodec: Codec {
  public typealias Value = LogRequest

  let _uint = Primitive.UInt()
  let _logTypeEnum = LogTypeEnumCodec()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: LogRequest) {
    var _flags: UInt = 0
    if value.type != nil { _flags |= 1 }
    if value.data != nil { _flags |= 2 }
    _uint.preencode(&state, _flags)
    if let _v = value.type { _logTypeEnum.preencode(&state, _v) }
    if let _v = value.data { _string.preencode(&state, _v) }
  }

  public func encode(_ state: inout State, _ value: LogRequest) throws {
    var _flags: UInt = 0
    if value.type != nil { _flags |= 1 }
    if value.data != nil { _flags |= 2 }
    try _uint.encode(&state, _flags)
    if let _v = value.type { try _logTypeEnum.encode(&state, _v) }
    if let _v = value.data { try _string.encode(&state, _v) }
  }

  public func decode(_ state: inout State) throws -> LogRequest {
    let _flags = try _uint.decode(&state)
    let type: LogTypeEnum? = _flags & 1 != 0 ? try _logTypeEnum.decode(&state) : nil
    let data: String? = _flags & 2 != 0 ? try _string.decode(&state) : nil
    return LogRequest(
      type: type,
      data: data
    )
  }
}

public let logRequest = LogRequestCodec()

// @wdk-core/workletStart-request
public struct WorkletStartRequest {
  public var enableDebugLogs: UInt?
  public var seedPhrase: String?
  public var seedBuffer: String?
  public var config: String

  public init(enableDebugLogs: UInt? = nil, seedPhrase: String? = nil, seedBuffer: String? = nil, config: String) {
    self.enableDebugLogs = enableDebugLogs
    self.seedPhrase = seedPhrase
    self.seedBuffer = seedBuffer
    self.config = config
  }
}

public struct WorkletStartRequestCodec: Codec {
  public typealias Value = WorkletStartRequest

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: WorkletStartRequest) {
    var _flags: UInt = 0
    if value.enableDebugLogs != nil { _flags |= 1 }
    if value.seedPhrase != nil { _flags |= 2 }
    if value.seedBuffer != nil { _flags |= 4 }
    _uint.preencode(&state, _flags)
    if let _v = value.enableDebugLogs { _uint.preencode(&state, _v) }
    if let _v = value.seedPhrase { _string.preencode(&state, _v) }
    if let _v = value.seedBuffer { _string.preencode(&state, _v) }
    _string.preencode(&state, value.config)
  }

  public func encode(_ state: inout State, _ value: WorkletStartRequest) throws {
    var _flags: UInt = 0
    if value.enableDebugLogs != nil { _flags |= 1 }
    if value.seedPhrase != nil { _flags |= 2 }
    if value.seedBuffer != nil { _flags |= 4 }
    try _uint.encode(&state, _flags)
    if let _v = value.enableDebugLogs { try _uint.encode(&state, _v) }
    if let _v = value.seedPhrase { try _string.encode(&state, _v) }
    if let _v = value.seedBuffer { try _string.encode(&state, _v) }
    try _string.encode(&state, value.config)
  }

  public func decode(_ state: inout State) throws -> WorkletStartRequest {
    let _flags = try _uint.decode(&state)
    let enableDebugLogs: UInt? = _flags & 1 != 0 ? try _uint.decode(&state) : nil
    let seedPhrase: String? = _flags & 2 != 0 ? try _string.decode(&state) : nil
    let seedBuffer: String? = _flags & 4 != 0 ? try _string.decode(&state) : nil
    let config = try _string.decode(&state)
    return WorkletStartRequest(
      enableDebugLogs: enableDebugLogs,
      seedPhrase: seedPhrase,
      seedBuffer: seedBuffer,
      config: config
    )
  }
}

public let workletStartRequest = WorkletStartRequestCodec()

// @wdk-core/workletStart-response
public struct WorkletStartResponse {
  public var status: String?

  public init(status: String? = nil) {
    self.status = status
  }
}

public struct WorkletStartResponseCodec: Codec {
  public typealias Value = WorkletStartResponse

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: WorkletStartResponse) {
    var _flags: UInt = 0
    if value.status != nil { _flags |= 1 }
    _uint.preencode(&state, _flags)
    if let _v = value.status { _string.preencode(&state, _v) }
  }

  public func encode(_ state: inout State, _ value: WorkletStartResponse) throws {
    var _flags: UInt = 0
    if value.status != nil { _flags |= 1 }
    try _uint.encode(&state, _flags)
    if let _v = value.status { try _string.encode(&state, _v) }
  }

  public func decode(_ state: inout State) throws -> WorkletStartResponse {
    let _flags = try _uint.decode(&state)
    let status: String? = _flags & 1 != 0 ? try _string.decode(&state) : nil
    return WorkletStartResponse(
      status: status
    )
  }
}

public let workletStartResponse = WorkletStartResponseCodec()

// @wdk-core/dispose-request
public struct DisposeRequest {

  public init() {
  }
}

public struct DisposeRequestCodec: Codec {
  public typealias Value = DisposeRequest


  public init() {}

  public func preencode(_ state: inout State, _ value: DisposeRequest) {
  }

  public func encode(_ state: inout State, _ value: DisposeRequest) throws {
  }

  public func decode(_ state: inout State) throws -> DisposeRequest {
    return DisposeRequest(
    )
  }
}

public let disposeRequest = DisposeRequestCodec()

// @wdk-core/callMethod-request
public struct CallMethodRequest {
  public var methodName: String
  public var network: String
  public var accountIndex: UInt
  public var args: String?
  public var options: String?

  public init(methodName: String, network: String, accountIndex: UInt, args: String? = nil, options: String? = nil) {
    self.methodName = methodName
    self.network = network
    self.accountIndex = accountIndex
    self.args = args
    self.options = options
  }
}

public struct CallMethodRequestCodec: Codec {
  public typealias Value = CallMethodRequest

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: CallMethodRequest) {
    _string.preencode(&state, value.methodName)
    _string.preencode(&state, value.network)
    _uint.preencode(&state, value.accountIndex)
    var _flags: UInt = 0
    if value.args != nil { _flags |= 1 }
    if value.options != nil { _flags |= 2 }
    _uint.preencode(&state, _flags)
    if let _v = value.args { _string.preencode(&state, _v) }
    if let _v = value.options { _string.preencode(&state, _v) }
  }

  public func encode(_ state: inout State, _ value: CallMethodRequest) throws {
    try _string.encode(&state, value.methodName)
    try _string.encode(&state, value.network)
    try _uint.encode(&state, value.accountIndex)
    var _flags: UInt = 0
    if value.args != nil { _flags |= 1 }
    if value.options != nil { _flags |= 2 }
    try _uint.encode(&state, _flags)
    if let _v = value.args { try _string.encode(&state, _v) }
    if let _v = value.options { try _string.encode(&state, _v) }
  }

  public func decode(_ state: inout State) throws -> CallMethodRequest {
    let methodName = try _string.decode(&state)
    let network = try _string.decode(&state)
    let accountIndex = try _uint.decode(&state)
    let _flags = try _uint.decode(&state)
    let args: String? = _flags & 1 != 0 ? try _string.decode(&state) : nil
    let options: String? = _flags & 2 != 0 ? try _string.decode(&state) : nil
    return CallMethodRequest(
      methodName: methodName,
      network: network,
      accountIndex: accountIndex,
      args: args,
      options: options
    )
  }
}

public let callMethodRequest = CallMethodRequestCodec()

// @wdk-core/callMethod-response
public struct CallMethodResponse {
  public var result: String?

  public init(result: String? = nil) {
    self.result = result
  }
}

public struct CallMethodResponseCodec: Codec {
  public typealias Value = CallMethodResponse

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: CallMethodResponse) {
    var _flags: UInt = 0
    if value.result != nil { _flags |= 1 }
    _uint.preencode(&state, _flags)
    if let _v = value.result { _string.preencode(&state, _v) }
  }

  public func encode(_ state: inout State, _ value: CallMethodResponse) throws {
    var _flags: UInt = 0
    if value.result != nil { _flags |= 1 }
    try _uint.encode(&state, _flags)
    if let _v = value.result { try _string.encode(&state, _v) }
  }

  public func decode(_ state: inout State) throws -> CallMethodResponse {
    let _flags = try _uint.decode(&state)
    let result: String? = _flags & 1 != 0 ? try _string.decode(&state) : nil
    return CallMethodResponse(
      result: result
    )
  }
}

public let callMethodResponse = CallMethodResponseCodec()

// @wdk-core/registerWallet-request
public struct RegisterWalletRequest {
  public var config: String

  public init(config: String) {
    self.config = config
  }
}

public struct RegisterWalletRequestCodec: Codec {
  public typealias Value = RegisterWalletRequest

  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: RegisterWalletRequest) {
    _string.preencode(&state, value.config)
  }

  public func encode(_ state: inout State, _ value: RegisterWalletRequest) throws {
    try _string.encode(&state, value.config)
  }

  public func decode(_ state: inout State) throws -> RegisterWalletRequest {
    let config = try _string.decode(&state)
    return RegisterWalletRequest(
      config: config
    )
  }
}

public let registerWalletRequest = RegisterWalletRequestCodec()

// @wdk-core/registerWallet-response
public struct RegisterWalletResponse {
  public var status: String?
  public var blockchains: String?

  public init(status: String? = nil, blockchains: String? = nil) {
    self.status = status
    self.blockchains = blockchains
  }
}

public struct RegisterWalletResponseCodec: Codec {
  public typealias Value = RegisterWalletResponse

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: RegisterWalletResponse) {
    var _flags: UInt = 0
    if value.status != nil { _flags |= 1 }
    if value.blockchains != nil { _flags |= 2 }
    _uint.preencode(&state, _flags)
    if let _v = value.status { _string.preencode(&state, _v) }
    if let _v = value.blockchains { _string.preencode(&state, _v) }
  }

  public func encode(_ state: inout State, _ value: RegisterWalletResponse) throws {
    var _flags: UInt = 0
    if value.status != nil { _flags |= 1 }
    if value.blockchains != nil { _flags |= 2 }
    try _uint.encode(&state, _flags)
    if let _v = value.status { try _string.encode(&state, _v) }
    if let _v = value.blockchains { try _string.encode(&state, _v) }
  }

  public func decode(_ state: inout State) throws -> RegisterWalletResponse {
    let _flags = try _uint.decode(&state)
    let status: String? = _flags & 1 != 0 ? try _string.decode(&state) : nil
    let blockchains: String? = _flags & 2 != 0 ? try _string.decode(&state) : nil
    return RegisterWalletResponse(
      status: status,
      blockchains: blockchains
    )
  }
}

public let registerWalletResponse = RegisterWalletResponseCodec()

// @wdk-core/registerProtocol-request
public struct RegisterProtocolRequest {
  public var config: String

  public init(config: String) {
    self.config = config
  }
}

public struct RegisterProtocolRequestCodec: Codec {
  public typealias Value = RegisterProtocolRequest

  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: RegisterProtocolRequest) {
    _string.preencode(&state, value.config)
  }

  public func encode(_ state: inout State, _ value: RegisterProtocolRequest) throws {
    try _string.encode(&state, value.config)
  }

  public func decode(_ state: inout State) throws -> RegisterProtocolRequest {
    let config = try _string.decode(&state)
    return RegisterProtocolRequest(
      config: config
    )
  }
}

public let registerProtocolRequest = RegisterProtocolRequestCodec()

// @wdk-core/registerProtocol-response
public struct RegisterProtocolResponse {
  public var status: String?

  public init(status: String? = nil) {
    self.status = status
  }
}

public struct RegisterProtocolResponseCodec: Codec {
  public typealias Value = RegisterProtocolResponse

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: RegisterProtocolResponse) {
    var _flags: UInt = 0
    if value.status != nil { _flags |= 1 }
    _uint.preencode(&state, _flags)
    if let _v = value.status { _string.preencode(&state, _v) }
  }

  public func encode(_ state: inout State, _ value: RegisterProtocolResponse) throws {
    var _flags: UInt = 0
    if value.status != nil { _flags |= 1 }
    try _uint.encode(&state, _flags)
    if let _v = value.status { try _string.encode(&state, _v) }
  }

  public func decode(_ state: inout State) throws -> RegisterProtocolResponse {
    let _flags = try _uint.decode(&state)
    let status: String? = _flags & 1 != 0 ? try _string.decode(&state) : nil
    return RegisterProtocolResponse(
      status: status
    )
  }
}

public let registerProtocolResponse = RegisterProtocolResponseCodec()

// @wdk-core/generateEntropyAndEncrypt-request
public struct GenerateEntropyAndEncryptRequest {
  public var wordCount: UInt

  public init(wordCount: UInt) {
    self.wordCount = wordCount
  }
}

public struct GenerateEntropyAndEncryptRequestCodec: Codec {
  public typealias Value = GenerateEntropyAndEncryptRequest

  let _uint = Primitive.UInt()

  public init() {}

  public func preencode(_ state: inout State, _ value: GenerateEntropyAndEncryptRequest) {
    _uint.preencode(&state, value.wordCount)
  }

  public func encode(_ state: inout State, _ value: GenerateEntropyAndEncryptRequest) throws {
    try _uint.encode(&state, value.wordCount)
  }

  public func decode(_ state: inout State) throws -> GenerateEntropyAndEncryptRequest {
    let wordCount = try _uint.decode(&state)
    return GenerateEntropyAndEncryptRequest(
      wordCount: wordCount
    )
  }
}

public let generateEntropyAndEncryptRequest = GenerateEntropyAndEncryptRequestCodec()

// @wdk-core/generateEntropyAndEncrypt-response
public struct GenerateEntropyAndEncryptResponse {
  public var encryptionKey: String?
  public var encryptedSeedBuffer: String?
  public var encryptedEntropyBuffer: String?

  public init(encryptionKey: String? = nil, encryptedSeedBuffer: String? = nil, encryptedEntropyBuffer: String? = nil) {
    self.encryptionKey = encryptionKey
    self.encryptedSeedBuffer = encryptedSeedBuffer
    self.encryptedEntropyBuffer = encryptedEntropyBuffer
  }
}

public struct GenerateEntropyAndEncryptResponseCodec: Codec {
  public typealias Value = GenerateEntropyAndEncryptResponse

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: GenerateEntropyAndEncryptResponse) {
    var _flags: UInt = 0
    if value.encryptionKey != nil { _flags |= 1 }
    if value.encryptedSeedBuffer != nil { _flags |= 2 }
    if value.encryptedEntropyBuffer != nil { _flags |= 4 }
    _uint.preencode(&state, _flags)
    if let _v = value.encryptionKey { _string.preencode(&state, _v) }
    if let _v = value.encryptedSeedBuffer { _string.preencode(&state, _v) }
    if let _v = value.encryptedEntropyBuffer { _string.preencode(&state, _v) }
  }

  public func encode(_ state: inout State, _ value: GenerateEntropyAndEncryptResponse) throws {
    var _flags: UInt = 0
    if value.encryptionKey != nil { _flags |= 1 }
    if value.encryptedSeedBuffer != nil { _flags |= 2 }
    if value.encryptedEntropyBuffer != nil { _flags |= 4 }
    try _uint.encode(&state, _flags)
    if let _v = value.encryptionKey { try _string.encode(&state, _v) }
    if let _v = value.encryptedSeedBuffer { try _string.encode(&state, _v) }
    if let _v = value.encryptedEntropyBuffer { try _string.encode(&state, _v) }
  }

  public func decode(_ state: inout State) throws -> GenerateEntropyAndEncryptResponse {
    let _flags = try _uint.decode(&state)
    let encryptionKey: String? = _flags & 1 != 0 ? try _string.decode(&state) : nil
    let encryptedSeedBuffer: String? = _flags & 2 != 0 ? try _string.decode(&state) : nil
    let encryptedEntropyBuffer: String? = _flags & 4 != 0 ? try _string.decode(&state) : nil
    return GenerateEntropyAndEncryptResponse(
      encryptionKey: encryptionKey,
      encryptedSeedBuffer: encryptedSeedBuffer,
      encryptedEntropyBuffer: encryptedEntropyBuffer
    )
  }
}

public let generateEntropyAndEncryptResponse = GenerateEntropyAndEncryptResponseCodec()

// @wdk-core/getMnemonicFromEntropy-request
public struct GetMnemonicFromEntropyRequest {
  public var encryptedEntropy: String
  public var encryptionKey: String

  public init(encryptedEntropy: String, encryptionKey: String) {
    self.encryptedEntropy = encryptedEntropy
    self.encryptionKey = encryptionKey
  }
}

public struct GetMnemonicFromEntropyRequestCodec: Codec {
  public typealias Value = GetMnemonicFromEntropyRequest

  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: GetMnemonicFromEntropyRequest) {
    _string.preencode(&state, value.encryptedEntropy)
    _string.preencode(&state, value.encryptionKey)
  }

  public func encode(_ state: inout State, _ value: GetMnemonicFromEntropyRequest) throws {
    try _string.encode(&state, value.encryptedEntropy)
    try _string.encode(&state, value.encryptionKey)
  }

  public func decode(_ state: inout State) throws -> GetMnemonicFromEntropyRequest {
    let encryptedEntropy = try _string.decode(&state)
    let encryptionKey = try _string.decode(&state)
    return GetMnemonicFromEntropyRequest(
      encryptedEntropy: encryptedEntropy,
      encryptionKey: encryptionKey
    )
  }
}

public let getMnemonicFromEntropyRequest = GetMnemonicFromEntropyRequestCodec()

// @wdk-core/getMnemonicFromEntropy-response
public struct GetMnemonicFromEntropyResponse {
  public var mnemonic: String?

  public init(mnemonic: String? = nil) {
    self.mnemonic = mnemonic
  }
}

public struct GetMnemonicFromEntropyResponseCodec: Codec {
  public typealias Value = GetMnemonicFromEntropyResponse

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: GetMnemonicFromEntropyResponse) {
    var _flags: UInt = 0
    if value.mnemonic != nil { _flags |= 1 }
    _uint.preencode(&state, _flags)
    if let _v = value.mnemonic { _string.preencode(&state, _v) }
  }

  public func encode(_ state: inout State, _ value: GetMnemonicFromEntropyResponse) throws {
    var _flags: UInt = 0
    if value.mnemonic != nil { _flags |= 1 }
    try _uint.encode(&state, _flags)
    if let _v = value.mnemonic { try _string.encode(&state, _v) }
  }

  public func decode(_ state: inout State) throws -> GetMnemonicFromEntropyResponse {
    let _flags = try _uint.decode(&state)
    let mnemonic: String? = _flags & 1 != 0 ? try _string.decode(&state) : nil
    return GetMnemonicFromEntropyResponse(
      mnemonic: mnemonic
    )
  }
}

public let getMnemonicFromEntropyResponse = GetMnemonicFromEntropyResponseCodec()

// @wdk-core/getSeedAndEntropyFromMnemonic-request
public struct GetSeedAndEntropyFromMnemonicRequest {
  public var mnemonic: String

  public init(mnemonic: String) {
    self.mnemonic = mnemonic
  }
}

public struct GetSeedAndEntropyFromMnemonicRequestCodec: Codec {
  public typealias Value = GetSeedAndEntropyFromMnemonicRequest

  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: GetSeedAndEntropyFromMnemonicRequest) {
    _string.preencode(&state, value.mnemonic)
  }

  public func encode(_ state: inout State, _ value: GetSeedAndEntropyFromMnemonicRequest) throws {
    try _string.encode(&state, value.mnemonic)
  }

  public func decode(_ state: inout State) throws -> GetSeedAndEntropyFromMnemonicRequest {
    let mnemonic = try _string.decode(&state)
    return GetSeedAndEntropyFromMnemonicRequest(
      mnemonic: mnemonic
    )
  }
}

public let getSeedAndEntropyFromMnemonicRequest = GetSeedAndEntropyFromMnemonicRequestCodec()

// @wdk-core/getSeedAndEntropyFromMnemonic-response
public struct GetSeedAndEntropyFromMnemonicResponse {
  public var encryptionKey: String?
  public var encryptedSeedBuffer: String?
  public var encryptedEntropyBuffer: String?

  public init(encryptionKey: String? = nil, encryptedSeedBuffer: String? = nil, encryptedEntropyBuffer: String? = nil) {
    self.encryptionKey = encryptionKey
    self.encryptedSeedBuffer = encryptedSeedBuffer
    self.encryptedEntropyBuffer = encryptedEntropyBuffer
  }
}

public struct GetSeedAndEntropyFromMnemonicResponseCodec: Codec {
  public typealias Value = GetSeedAndEntropyFromMnemonicResponse

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: GetSeedAndEntropyFromMnemonicResponse) {
    var _flags: UInt = 0
    if value.encryptionKey != nil { _flags |= 1 }
    if value.encryptedSeedBuffer != nil { _flags |= 2 }
    if value.encryptedEntropyBuffer != nil { _flags |= 4 }
    _uint.preencode(&state, _flags)
    if let _v = value.encryptionKey { _string.preencode(&state, _v) }
    if let _v = value.encryptedSeedBuffer { _string.preencode(&state, _v) }
    if let _v = value.encryptedEntropyBuffer { _string.preencode(&state, _v) }
  }

  public func encode(_ state: inout State, _ value: GetSeedAndEntropyFromMnemonicResponse) throws {
    var _flags: UInt = 0
    if value.encryptionKey != nil { _flags |= 1 }
    if value.encryptedSeedBuffer != nil { _flags |= 2 }
    if value.encryptedEntropyBuffer != nil { _flags |= 4 }
    try _uint.encode(&state, _flags)
    if let _v = value.encryptionKey { try _string.encode(&state, _v) }
    if let _v = value.encryptedSeedBuffer { try _string.encode(&state, _v) }
    if let _v = value.encryptedEntropyBuffer { try _string.encode(&state, _v) }
  }

  public func decode(_ state: inout State) throws -> GetSeedAndEntropyFromMnemonicResponse {
    let _flags = try _uint.decode(&state)
    let encryptionKey: String? = _flags & 1 != 0 ? try _string.decode(&state) : nil
    let encryptedSeedBuffer: String? = _flags & 2 != 0 ? try _string.decode(&state) : nil
    let encryptedEntropyBuffer: String? = _flags & 4 != 0 ? try _string.decode(&state) : nil
    return GetSeedAndEntropyFromMnemonicResponse(
      encryptionKey: encryptionKey,
      encryptedSeedBuffer: encryptedSeedBuffer,
      encryptedEntropyBuffer: encryptedEntropyBuffer
    )
  }
}

public let getSeedAndEntropyFromMnemonicResponse = GetSeedAndEntropyFromMnemonicResponseCodec()

// @wdk-core/initializeWDK-request
public struct InitializeWDKRequest {
  public var seedPhrase: String?
  public var encryptionKey: String?
  public var encryptedSeed: String?
  public var config: String

  public init(seedPhrase: String? = nil, encryptionKey: String? = nil, encryptedSeed: String? = nil, config: String) {
    self.seedPhrase = seedPhrase
    self.encryptionKey = encryptionKey
    self.encryptedSeed = encryptedSeed
    self.config = config
  }
}

public struct InitializeWDKRequestCodec: Codec {
  public typealias Value = InitializeWDKRequest

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: InitializeWDKRequest) {
    var _flags: UInt = 0
    if value.seedPhrase != nil { _flags |= 1 }
    if value.encryptionKey != nil { _flags |= 2 }
    if value.encryptedSeed != nil { _flags |= 4 }
    _uint.preencode(&state, _flags)
    if let _v = value.seedPhrase { _string.preencode(&state, _v) }
    if let _v = value.encryptionKey { _string.preencode(&state, _v) }
    if let _v = value.encryptedSeed { _string.preencode(&state, _v) }
    _string.preencode(&state, value.config)
  }

  public func encode(_ state: inout State, _ value: InitializeWDKRequest) throws {
    var _flags: UInt = 0
    if value.seedPhrase != nil { _flags |= 1 }
    if value.encryptionKey != nil { _flags |= 2 }
    if value.encryptedSeed != nil { _flags |= 4 }
    try _uint.encode(&state, _flags)
    if let _v = value.seedPhrase { try _string.encode(&state, _v) }
    if let _v = value.encryptionKey { try _string.encode(&state, _v) }
    if let _v = value.encryptedSeed { try _string.encode(&state, _v) }
    try _string.encode(&state, value.config)
  }

  public func decode(_ state: inout State) throws -> InitializeWDKRequest {
    let _flags = try _uint.decode(&state)
    let seedPhrase: String? = _flags & 1 != 0 ? try _string.decode(&state) : nil
    let encryptionKey: String? = _flags & 2 != 0 ? try _string.decode(&state) : nil
    let encryptedSeed: String? = _flags & 4 != 0 ? try _string.decode(&state) : nil
    let config = try _string.decode(&state)
    return InitializeWDKRequest(
      seedPhrase: seedPhrase,
      encryptionKey: encryptionKey,
      encryptedSeed: encryptedSeed,
      config: config
    )
  }
}

public let initializeWDKRequest = InitializeWDKRequestCodec()

// @wdk-core/initializeWDK-response
public struct InitializeWDKResponse {
  public var status: String?

  public init(status: String? = nil) {
    self.status = status
  }
}

public struct InitializeWDKResponseCodec: Codec {
  public typealias Value = InitializeWDKResponse

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: InitializeWDKResponse) {
    var _flags: UInt = 0
    if value.status != nil { _flags |= 1 }
    _uint.preencode(&state, _flags)
    if let _v = value.status { _string.preencode(&state, _v) }
  }

  public func encode(_ state: inout State, _ value: InitializeWDKResponse) throws {
    var _flags: UInt = 0
    if value.status != nil { _flags |= 1 }
    try _uint.encode(&state, _flags)
    if let _v = value.status { try _string.encode(&state, _v) }
  }

  public func decode(_ state: inout State) throws -> InitializeWDKResponse {
    let _flags = try _uint.decode(&state)
    let status: String? = _flags & 1 != 0 ? try _string.decode(&state) : nil
    return InitializeWDKResponse(
      status: status
    )
  }
}

public let initializeWDKResponse = InitializeWDKResponseCodec()

// @wdk-core/resetWdkWallets-request
public struct ResetWdkWalletsRequest {
  public var config: String

  public init(config: String) {
    self.config = config
  }
}

public struct ResetWdkWalletsRequestCodec: Codec {
  public typealias Value = ResetWdkWalletsRequest

  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: ResetWdkWalletsRequest) {
    _string.preencode(&state, value.config)
  }

  public func encode(_ state: inout State, _ value: ResetWdkWalletsRequest) throws {
    try _string.encode(&state, value.config)
  }

  public func decode(_ state: inout State) throws -> ResetWdkWalletsRequest {
    let config = try _string.decode(&state)
    return ResetWdkWalletsRequest(
      config: config
    )
  }
}

public let resetWdkWalletsRequest = ResetWdkWalletsRequestCodec()

// @wdk-core/resetWdkWallets-response
public struct ResetWdkWalletsResponse {
  public var status: String?

  public init(status: String? = nil) {
    self.status = status
  }
}

public struct ResetWdkWalletsResponseCodec: Codec {
  public typealias Value = ResetWdkWalletsResponse

  let _uint = Primitive.UInt()
  let _string = Primitive.UTF8()

  public init() {}

  public func preencode(_ state: inout State, _ value: ResetWdkWalletsResponse) {
    var _flags: UInt = 0
    if value.status != nil { _flags |= 1 }
    _uint.preencode(&state, _flags)
    if let _v = value.status { _string.preencode(&state, _v) }
  }

  public func encode(_ state: inout State, _ value: ResetWdkWalletsResponse) throws {
    var _flags: UInt = 0
    if value.status != nil { _flags |= 1 }
    try _uint.encode(&state, _flags)
    if let _v = value.status { try _string.encode(&state, _v) }
  }

  public func decode(_ state: inout State) throws -> ResetWdkWalletsResponse {
    let _flags = try _uint.decode(&state)
    let status: String? = _flags & 1 != 0 ? try _string.decode(&state) : nil
    return ResetWdkWalletsResponse(
      status: status
    )
  }
}

public let resetWdkWalletsResponse = ResetWdkWalletsResponseCodec()
