// swift-tools-version: 5.9

import PackageDescription

let package = Package(
    name: "WdkSwiftCore",
    platforms: [
        .iOS(.v14),
        .macOS(.v11)
    ],
    products: [
        .library(
            name: "WdkSwiftCore",
            targets: ["WdkSwiftCore"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/holepunchto/bare-kit-swift", branch: "main"),
        .package(url: "https://github.com/holepunchto/bare-rpc-swift", branch: "main"),
        .package(url: "https://github.com/holepunchto/compact-encoding-swift", branch: "main")
    ],
    targets: [
        // Generated by pear-wrk-wdk `npm run gen:swift` (hyperschema-swift) — vendored, do not edit.
        .target(
            name: "Schema",
            dependencies: [
                .product(name: "CompactEncoding", package: "compact-encoding-swift"),
            ]
        ),
        // Generated by pear-wrk-wdk `npm run gen:swift` (hrpc-swift) — vendored, do not edit.
        .target(
            name: "HRPC",
            dependencies: [
                .product(name: "BareRPC", package: "bare-rpc-swift"),
                "Schema",
            ]
        ),
        .target(
            name: "WdkSwiftCore",
            dependencies: [
                .product(name: "BareKit", package: "bare-kit-swift"),
                .product(name: "BareRPC", package: "bare-rpc-swift"),
                "HRPC",
                "Schema",
            ]
        ),
        .testTarget(
            name: "WdkSwiftCoreTests",
            dependencies: ["WdkSwiftCore"]
        ),
    ]
)
