// This file is autogenerated by the hrpc compiler

import BareRPC
import CompactEncoding
import Foundation
import Schema

public class HRPC {
  private let _rpc: RPC
  private let _forwarder: _HRPCDelegateForwarder
  private var _handlers: [String: Any] = [:]

  public init<D: RPCDelegate>(delegate: D) {
    let forwarder = _HRPCDelegateForwarder(transport: delegate)
    self._rpc = RPC(delegate: forwarder)
    self._forwarder = forwarder
    forwarder.hrpc = self
  }

  public func receive(_ data: Data) async {
    await self._rpc.receive(data)
  }

  // Send-only — client (fire and forget)
  public func log(_ args: LogRequest? = nil) async throws {
    let encoded = try args.map { try _encode(logRequest, $0) }
    await _rpc.event(0, data: encoded)
  }

  public func onLog(_ handler: @escaping (LogRequest?) async -> Void) {
    _handlers["@wdk-core/log"] = handler
  }

  // Request/response — client
  public func workletStart(_ args: WorkletStartRequest? = nil) async throws -> WorkletStartResponse {
    let encoded = try args.map { try _encode(workletStartRequest, $0) }
    guard let raw = try await _rpc.request(1, data: encoded) else {
      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")
    }
    return try _decode(workletStartResponse, raw)
  }

  public func onWorkletStart(_ handler: @escaping (WorkletStartRequest?) async throws -> WorkletStartResponse) {
    _handlers["@wdk-core/worklet-start"] = handler
  }

  // Send-only — client (fire and forget)
  public func dispose(_ args: DisposeRequest? = nil) async throws {
    let encoded = try args.map { try _encode(disposeRequest, $0) }
    await _rpc.event(2, data: encoded)
  }

  public func onDispose(_ handler: @escaping (DisposeRequest?) async -> Void) {
    _handlers["@wdk-core/dispose"] = handler
  }

  // Request/response — client
  public func callMethod(_ args: CallMethodRequest? = nil) async throws -> CallMethodResponse {
    let encoded = try args.map { try _encode(callMethodRequest, $0) }
    guard let raw = try await _rpc.request(3, data: encoded) else {
      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")
    }
    return try _decode(callMethodResponse, raw)
  }

  public func onCallMethod(_ handler: @escaping (CallMethodRequest?) async throws -> CallMethodResponse) {
    _handlers["@wdk-core/call-method"] = handler
  }

  // Request/response — client
  public func generateEntropyAndEncrypt(_ args: GenerateEntropyAndEncryptRequest? = nil) async throws -> GenerateEntropyAndEncryptResponse {
    let encoded = try args.map { try _encode(generateEntropyAndEncryptRequest, $0) }
    guard let raw = try await _rpc.request(4, data: encoded) else {
      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")
    }
    return try _decode(generateEntropyAndEncryptResponse, raw)
  }

  public func onGenerateEntropyAndEncrypt(_ handler: @escaping (GenerateEntropyAndEncryptRequest?) async throws -> GenerateEntropyAndEncryptResponse) {
    _handlers["@wdk-core/generate-entropy-and-encrypt"] = handler
  }

  // Request/response — client
  public func getMnemonicFromEntropy(_ args: GetMnemonicFromEntropyRequest? = nil) async throws -> GetMnemonicFromEntropyResponse {
    let encoded = try args.map { try _encode(getMnemonicFromEntropyRequest, $0) }
    guard let raw = try await _rpc.request(5, data: encoded) else {
      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")
    }
    return try _decode(getMnemonicFromEntropyResponse, raw)
  }

  public func onGetMnemonicFromEntropy(_ handler: @escaping (GetMnemonicFromEntropyRequest?) async throws -> GetMnemonicFromEntropyResponse) {
    _handlers["@wdk-core/get-mnemonic-from-entropy"] = handler
  }

  // Request/response — client
  public func initializeWdk(_ args: InitializeWDKRequest? = nil) async throws -> InitializeWDKResponse {
    let encoded = try args.map { try _encode(initializeWDKRequest, $0) }
    guard let raw = try await _rpc.request(6, data: encoded) else {
      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")
    }
    return try _decode(initializeWDKResponse, raw)
  }

  public func onInitializeWdk(_ handler: @escaping (InitializeWDKRequest?) async throws -> InitializeWDKResponse) {
    _handlers["@wdk-core/initialize-wdk"] = handler
  }

  // Request/response — client
  public func getSeedAndEntropyFromMnemonic(_ args: GetSeedAndEntropyFromMnemonicRequest? = nil) async throws -> GetSeedAndEntropyFromMnemonicResponse {
    let encoded = try args.map { try _encode(getSeedAndEntropyFromMnemonicRequest, $0) }
    guard let raw = try await _rpc.request(7, data: encoded) else {
      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")
    }
    return try _decode(getSeedAndEntropyFromMnemonicResponse, raw)
  }

  public func onGetSeedAndEntropyFromMnemonic(_ handler: @escaping (GetSeedAndEntropyFromMnemonicRequest?) async throws -> GetSeedAndEntropyFromMnemonicResponse) {
    _handlers["@wdk-core/get-seed-and-entropy-from-mnemonic"] = handler
  }

  // Request/response — client
  public func registerWallet(_ args: RegisterWalletRequest? = nil) async throws -> RegisterWalletResponse {
    let encoded = try args.map { try _encode(registerWalletRequest, $0) }
    guard let raw = try await _rpc.request(8, data: encoded) else {
      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")
    }
    return try _decode(registerWalletResponse, raw)
  }

  public func onRegisterWallet(_ handler: @escaping (RegisterWalletRequest?) async throws -> RegisterWalletResponse) {
    _handlers["@wdk-core/register-wallet"] = handler
  }

  // Request/response — client
  public func registerProtocol(_ args: RegisterProtocolRequest? = nil) async throws -> RegisterProtocolResponse {
    let encoded = try args.map { try _encode(registerProtocolRequest, $0) }
    guard let raw = try await _rpc.request(9, data: encoded) else {
      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")
    }
    return try _decode(registerProtocolResponse, raw)
  }

  public func onRegisterProtocol(_ handler: @escaping (RegisterProtocolRequest?) async throws -> RegisterProtocolResponse) {
    _handlers["@wdk-core/register-protocol"] = handler
  }

  // Request/response — client
  public func resetWdkWallets(_ args: ResetWdkWalletsRequest? = nil) async throws -> ResetWdkWalletsResponse {
    let encoded = try args.map { try _encode(resetWdkWalletsRequest, $0) }
    guard let raw = try await _rpc.request(10, data: encoded) else {
      throw RPCRemoteError(message: "Missing response", code: "MISSING_RESPONSE")
    }
    return try _decode(resetWdkWalletsResponse, raw)
  }

  public func onResetWdkWallets(_ handler: @escaping (ResetWdkWalletsRequest?) async throws -> ResetWdkWalletsResponse) {
    _handlers["@wdk-core/reset-wdk-wallets"] = handler
  }

  fileprivate func _dispatchRequest(_ req: IncomingRequest) async {
    await _dispatchNormal(req)
  }
  private func _dispatchNormal(_ req: IncomingRequest) async {
    switch req.command {
    case 1:   // @wdk-core/worklet-start
      guard let handler = _handlers["@wdk-core/worklet-start"] as? (WorkletStartRequest?) async throws -> WorkletStartResponse else { await req.reject("No handler registered", code: "NO_HANDLER"); return }
      do {
        let args: WorkletStartRequest? = try req.data.map { try _decode(workletStartRequest, $0) }
        let response = try await handler(args)
        await req.reply(try _encode(workletStartResponse, response))
      } catch {
        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")
      }
    case 3:   // @wdk-core/call-method
      guard let handler = _handlers["@wdk-core/call-method"] as? (CallMethodRequest?) async throws -> CallMethodResponse else { await req.reject("No handler registered", code: "NO_HANDLER"); return }
      do {
        let args: CallMethodRequest? = try req.data.map { try _decode(callMethodRequest, $0) }
        let response = try await handler(args)
        await req.reply(try _encode(callMethodResponse, response))
      } catch {
        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")
      }
    case 4:   // @wdk-core/generate-entropy-and-encrypt
      guard let handler = _handlers["@wdk-core/generate-entropy-and-encrypt"] as? (GenerateEntropyAndEncryptRequest?) async throws -> GenerateEntropyAndEncryptResponse else { await req.reject("No handler registered", code: "NO_HANDLER"); return }
      do {
        let args: GenerateEntropyAndEncryptRequest? = try req.data.map { try _decode(generateEntropyAndEncryptRequest, $0) }
        let response = try await handler(args)
        await req.reply(try _encode(generateEntropyAndEncryptResponse, response))
      } catch {
        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")
      }
    case 5:   // @wdk-core/get-mnemonic-from-entropy
      guard let handler = _handlers["@wdk-core/get-mnemonic-from-entropy"] as? (GetMnemonicFromEntropyRequest?) async throws -> GetMnemonicFromEntropyResponse else { await req.reject("No handler registered", code: "NO_HANDLER"); return }
      do {
        let args: GetMnemonicFromEntropyRequest? = try req.data.map { try _decode(getMnemonicFromEntropyRequest, $0) }
        let response = try await handler(args)
        await req.reply(try _encode(getMnemonicFromEntropyResponse, response))
      } catch {
        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")
      }
    case 6:   // @wdk-core/initialize-wdk
      guard let handler = _handlers["@wdk-core/initialize-wdk"] as? (InitializeWDKRequest?) async throws -> InitializeWDKResponse else { await req.reject("No handler registered", code: "NO_HANDLER"); return }
      do {
        let args: InitializeWDKRequest? = try req.data.map { try _decode(initializeWDKRequest, $0) }
        let response = try await handler(args)
        await req.reply(try _encode(initializeWDKResponse, response))
      } catch {
        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")
      }
    case 7:   // @wdk-core/get-seed-and-entropy-from-mnemonic
      guard let handler = _handlers["@wdk-core/get-seed-and-entropy-from-mnemonic"] as? (GetSeedAndEntropyFromMnemonicRequest?) async throws -> GetSeedAndEntropyFromMnemonicResponse else { await req.reject("No handler registered", code: "NO_HANDLER"); return }
      do {
        let args: GetSeedAndEntropyFromMnemonicRequest? = try req.data.map { try _decode(getSeedAndEntropyFromMnemonicRequest, $0) }
        let response = try await handler(args)
        await req.reply(try _encode(getSeedAndEntropyFromMnemonicResponse, response))
      } catch {
        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")
      }
    case 8:   // @wdk-core/register-wallet
      guard let handler = _handlers["@wdk-core/register-wallet"] as? (RegisterWalletRequest?) async throws -> RegisterWalletResponse else { await req.reject("No handler registered", code: "NO_HANDLER"); return }
      do {
        let args: RegisterWalletRequest? = try req.data.map { try _decode(registerWalletRequest, $0) }
        let response = try await handler(args)
        await req.reply(try _encode(registerWalletResponse, response))
      } catch {
        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")
      }
    case 9:   // @wdk-core/register-protocol
      guard let handler = _handlers["@wdk-core/register-protocol"] as? (RegisterProtocolRequest?) async throws -> RegisterProtocolResponse else { await req.reject("No handler registered", code: "NO_HANDLER"); return }
      do {
        let args: RegisterProtocolRequest? = try req.data.map { try _decode(registerProtocolRequest, $0) }
        let response = try await handler(args)
        await req.reply(try _encode(registerProtocolResponse, response))
      } catch {
        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")
      }
    case 10:   // @wdk-core/reset-wdk-wallets
      guard let handler = _handlers["@wdk-core/reset-wdk-wallets"] as? (ResetWdkWalletsRequest?) async throws -> ResetWdkWalletsResponse else { await req.reject("No handler registered", code: "NO_HANDLER"); return }
      do {
        let args: ResetWdkWalletsRequest? = try req.data.map { try _decode(resetWdkWalletsRequest, $0) }
        let response = try await handler(args)
        await req.reply(try _encode(resetWdkWalletsResponse, response))
      } catch {
        await req.reject(error.localizedDescription, code: "HANDLER_ERROR")
      }
    default:
      await req.reject("Unknown command", code: "UNKNOWN_COMMAND")
    }
  }
  fileprivate func _dispatchEvent(_ event: IncomingEvent) async {
    switch event.command {
    case 0:   // @wdk-core/log
      guard let handler = _handlers["@wdk-core/log"] as? (LogRequest?) async -> Void else { return }
      do {
        let args: LogRequest? = try event.data.map { try _decode(logRequest, $0) }
        await handler(args)
      } catch {
        _forwarder.transport.rpc(_rpc, didFailWith: error)
      }
    case 2:   // @wdk-core/dispose
      guard let handler = _handlers["@wdk-core/dispose"] as? (DisposeRequest?) async -> Void else { return }
      do {
        let args: DisposeRequest? = try event.data.map { try _decode(disposeRequest, $0) }
        await handler(args)
      } catch {
        _forwarder.transport.rpc(_rpc, didFailWith: error)
      }
    default:
      break
    }
  }

  private func _encode<C: Codec>(_ codec: C, _ value: C.Value) throws -> Data {
    var state = State()
    codec.preencode(&state, value)
    state.allocate()
    try codec.encode(&state, value)
    return state.buffer
  }

  private func _decode<C: Codec>(_ codec: C, _ data: Data) throws -> C.Value {
    var state = State(data)
    return try codec.decode(&state)
  }
}

private final class _HRPCDelegateForwarder: RPCDelegate {
  let transport: any RPCDelegate
  weak var hrpc: HRPC?

  init<D: RPCDelegate>(transport: D) {
    self.transport = transport
  }

  func rpc(_ rpc: RPC, send data: Data) {
    transport.rpc(rpc, send: data)
  }

  func rpc(_ rpc: RPC, didFailWith error: Error) {
    transport.rpc(rpc, didFailWith: error)
  }

  func rpc(_ rpc: RPC, didReceiveRequest req: IncomingRequest) async throws {
    await hrpc?._dispatchRequest(req)
  }

  func rpc(_ rpc: RPC, didReceiveEvent event: IncomingEvent) async {
    await hrpc?._dispatchEvent(event)
  }
}
